lidar:
- driver:
    channel_fov_filter_path: Your channel fov filter file path
    default_frame_frequency: 10.0
    device_fault_port: 0
    device_udp_src_port: 0
    distance_correction_flag: false
    echo_mode_filter: 0
    enable_packet_loss_tool: true
    fov_end: -1
    fov_start: -1
    frame_frequency: 0
    frame_start_azimuth: 0
    lidar_udp_type:
      caFile: ''
      certFile: ''
      correction_file_path: Your correction file path
      device_ip_address: 192.168.3.201
      fault_message_port: 0
      firetimes_path: Your firetime file path
      host_ip_address: 192.168.3.100
      host_ptc_port: 0
      multicast_ip_address: ''
      privateKeyFile: ''
      ptc_connect_timeout: -1
      ptc_mode: 0
      ptc_port: 9347
      recv_point_cloud_timeout: -1
      speed: -1
      standby_mode: -1
      udp_port: 2368
      use_ptc_connected: true
    multi_fov_filter_ranges: ''
    pcap_type:
      correction_file_path: Your correction file path
      firetimes_path: Your firetime file path
      pcap_path: Your pcap file
      pcap_play_in_loop: false
      pcap_play_synchronization: true
      play_rate_: 1.0
    pitch: 0
    roll: 0
    rosbag_type:
      correction_file_path: Your correction file path
      firetimes_path: Your firetime file path
    serial_type:
      correction_file_path: Your correction file path
      correction_save_path: ''
      point_cloud_baudrate: 3125000
      rs232_com: Your serial port name for sending cmd
      rs485_com: Your serial port name for receiving point cloud
    source_type: 1
    thread_num: 5
    transform_flag: false
    use_gpu: true 
    use_timestamp_type: 0
    x: 0
    xt_spot_correction: false
    y: 0
    yaw: 0
    z: 0
  ros:
    ros_frame_id: hesai_lidar
    ros_recv_packet_topic: /lidar_packets
    ros_send_imu_topic: /lidar_imu
    ros_send_packet_loss_topic: /lidar_packets_loss
    ros_send_packet_topic: /lidar_packets
    ros_send_point_cloud_topic: /scan_cloud
    send_imu_ros: true
    send_packet_ros: false
    send_point_cloud_ros: true
